import os
import json
from datetime import datetime

def generate_project_state(repo_dir):
    manifest_path = os.path.join(repo_dir, "REPOSITORY_MANIFEST.json")
    if os.path.exists(manifest_path):
        with open(manifest_path, "r") as f:
            manifest = json.load(f)
    else:
        manifest = {"repository_version": "Unknown", "supported_protocol_versions": ["Unknown"]}
    
    state_md = f"""# Project State
*Automatically generated by Chief of Staff. Do not edit.*

**Last Updated:** {datetime.utcnow().isoformat()}Z

## Repository Context
- **Current Epoch:** Epoch I (Recovery)
- **Repository Version:** {manifest.get('repository_version')}
- **Protocol Version:** {', '.join(manifest.get('supported_protocol_versions', []))}
- **Ledger Version:** v1
- **Current Branch:** feature/infrastructure-foundations

## Execution State
- **Current Batch:** Batch 3 (Pending Authorization)
- **Last Successful Run:** Consistency Audit (Batch 3)
- **Next Planned Action:** Resolve Open Semantic Findings
- **Run Status:** VALIDATION_PENDING

## Health & Risks
- **Blocked By:** Semantic Adjudication Required
- **Open Findings:** 8 (Batch 3 Semantic Findings)
- **Open Decisions:** 0
- **Known Risks:** None
"""
    state_path = os.path.join(repo_dir, "docs", "PROJECT_STATE.md")
    with open(state_path, "w", encoding="utf-8") as f:
        f.write(state_md)

if __name__ == "__main__":
    repo_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    generate_project_state(repo_dir)
