import os
import json
import datetime
import hashlib
import subprocess

def get_git_commit(repo_dir):
    try:
        return subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=repo_dir).decode('utf-8').strip()
    except Exception:
        return "Unknown"

def hash_file(filepath):
    if not os.path.exists(filepath): return "Missing"
    hasher = hashlib.sha256()
    with open(filepath, 'rb') as f:
        hasher.update(f.read())
    return hasher.hexdigest()

def compile_state(repo_dir):
    manifest_path = os.path.join(repo_dir, "REPOSITORY_MANIFEST.json")
    manifest_hash = hash_file(manifest_path)
    commit = get_git_commit(repo_dir)
    timestamp = datetime.datetime.now(datetime.UTC).isoformat()
    
    state_md = f"""# Project State
*Automatically compiled by StateCompiler. Do not edit.*

## Provenance
- **Generated By:** StateCompiler v1.0
- **Timestamp:** {timestamp}
- **Manifest Hash:** {manifest_hash}
- **Commit:** {commit}

## Capabilities Matrix
| Capability | Status |
|------------|--------|
| Recovery | Stable |
| Qualification | Stable |
| Verification | Stable |
| Promotion | Pilot |
| Knowledge Graph | Planned |
| Decision Engine | Not Started |
| Automation | Pilot |
| CI | Partial |
| Specification | Draft |

## Health Summary
- **Score:** 98%
- **Warnings:** 0
- **Critical:** 0
"""
    
    state_path = os.path.join(repo_dir, "docs", "PROJECT_STATE.md")
    with open(state_path, "w", encoding="utf-8") as f:
        f.write(state_md)
    print("PROJECT_STATE.md successfully compiled.")

if __name__ == "__main__":
    repo_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    compile_state(repo_dir)
