import os
import json
import datetime
import hashlib
import subprocess

def get_git_commit(repo_dir):
    try:
        return subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=repo_dir).decode('utf-8').strip()
    except Exception:
        return "Unknown"

def hash_file(filepath):
    if not os.path.exists(filepath): return "Missing"
    hasher = hashlib.sha256()
    with open(filepath, 'rb') as f:
        hasher.update(f.read())
    return hasher.hexdigest()

def compile_state(repo_dir):
    bios_path = os.path.join(repo_dir, "REPOSITORY_BIOS.json")
    bios_hash = hash_file(bios_path)
    commit = get_git_commit(repo_dir)
    timestamp = datetime.datetime.now(datetime.UTC).isoformat()
    
    # Capabilities
    caps_dir = os.path.join(repo_dir, "capabilities")
    caps = {}
    if os.path.exists(caps_dir):
        for f in os.listdir(caps_dir):
            if f.endswith(".json"):
                with open(os.path.join(caps_dir, f), "r") as cf:
                    data = json.load(cf)
                    caps[data.get("capability", "Unknown")] = data.get("status", "Unknown")
    
    # SMART Repository Health / Self-Awareness
    try:
        subprocess.check_output([sys.executable, "-m", "pytest", os.path.join(repo_dir, "tests")], stderr=subprocess.STDOUT)
        tests_passing = True
    except subprocess.CalledProcessError:
        tests_passing = False
    except FileNotFoundError:
        tests_passing = False

    try:
        last_commit_date_str = subprocess.check_output(['git', 'log', '-1', '--format=%cd', '--date=iso-strict'], cwd=repo_dir).decode('utf-8').strip()
        last_commit_date = datetime.datetime.fromisoformat(last_commit_date_str.replace('Z', '+00:00'))
        staleness_days = (datetime.datetime.now(datetime.timezone.utc) - last_commit_date).days
    except Exception:
        staleness_days = 0

    adr_dir = os.path.join(repo_dir, "constitution", "adr")
    adrs_accumulated = len([f for f in os.listdir(adr_dir) if f.endswith(".md")]) if os.path.exists(adr_dir) else 0

    maintenance_recommended = not tests_passing or staleness_days > 30 or adrs_accumulated > 20

    state_json = {
        "schema_version": "1.0",
        "provenance": {
            "generated_by": "StateCompiler v1.3",
            "timestamp": timestamp,
            "bios_hash": bios_hash,
            "commit": commit
        },
        "capabilities": caps,
        "health": {
            "tests_passing": tests_passing,
            "staleness_days": staleness_days,
            "adrs_accumulated": adrs_accumulated,
            "maintenance_recommended": maintenance_recommended
        }
    }
    
    json_path = os.path.join(repo_dir, "docs", "PROJECT_STATE.json")
    md_path = os.path.join(repo_dir, "docs", "PROJECT_STATE.md")
    
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(state_json, f, indent=2)
        
    md_content = f"""# Project State
*Automatically compiled by StateCompiler. Do not edit.*

## Provenance
- **Generated By:** {state_json['provenance']['generated_by']}
- **Timestamp:** {state_json['provenance']['timestamp']}
- **BIOS Hash:** {state_json['provenance']['bios_hash']}
- **Commit:** {state_json['provenance']['commit']}

## Capabilities Matrix
| Capability | Status |
|------------|--------|
"""
    for cap, status in caps.items():
        md_content += f"| {cap} | {status} |\n"
        
    md_content += f"""
## Repository Health (SMART)
- **Tests Passing:** {'Yes' if tests_passing else 'No'}
- **Staleness:** {staleness_days} days since last commit
- **ADRs Accumulated:** {adrs_accumulated}
- **Maintenance Recommended:** {'Yes' if maintenance_recommended else 'No'}
"""
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    print("PROJECT_STATE.json and PROJECT_STATE.md successfully compiled.")

if __name__ == "__main__":
    repo_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    compile_state(repo_dir)
